config/routes.rb
Rails.application.routes.draw do



root "drinks#index"

resources :drinks
resources :shelves
resources :ingredients, only: [:new, :create]

get '/shelves/:shelf_id/add_ingredient/:id' => 'shelves#add_ingredient', as: :add_ingredient
get '/shelves/:shelf_id/remove_ingredient/:id' => 'shelves#remove_ingredient', as: :remove_ingredient

end

app/models/direction.rb
class Direction < ActiveRecord::Base
  belongs_to :drink
end

app/models/drink.rb
class Drink < ActiveRecord::Base

  has_many :ingredients
  has_many :directions, dependent: :destroy

  validates :name, presence: true, uniqueness: true
  validates :description, presence: true

  accepts_nested_attributes_for :ingredients, :reject_if => :all_blank, :allow_destroy => true

  accepts_nested_attributes_for :directions, :reject_if => :all_blank, :allow_destroy => true


end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  belongs_to :drink
  belongs_to :shelf

  validates :name, presence: true
  validates :category, presence: true

end

app/models/shelf.rb
class Shelf < ActiveRecord::Base
  has_many :ingredients, dependent: :nullify
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to '/login' unless current_user
  end

end

app/controllers/drinks_controller.rb
class DrinksController < ApplicationController

  before_action :find_drink, only: [:show, :edit, :update, :destroy]

  def index
    @drinks = Drink.all
  end

  def show
    @drink = Drink.find params[:id]
  end

  def new
    @drink = Drink.new
    @drink.ingredients.build
  end

  def create 
    @drink = Drink.new drink_params
      if @drink.save
        redirect_to @drink
      else
        render :new
      end
  end

  def edit
  end

  def update
    if @drink.update drink_params
      redirect_to @drink
    else
      render :edit
    end
  end

  def destroy
    @drink.destroy
    redirect_to root_path
  end

private

  def find_drink
    @drink = Drink.find params[:id]
  end

  def drink_params
    params.require(:drink).permit(
                                  :name, :description, 
                                  ingredients_attributes: [:name, :category],
                                  directions_attributes: [:id, :step, :_destroy]
                                  )
  end 

end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  
  def new
    @ingredient = Ingredient.new
    @ingredients = Ingredient.all
  end

  def create
    @ingredient = Ingredient.new ingredient_params
    respond_to do |format|
      if @ingredient.save
        format.html { render :new }
        format.js { render }
      else
        format.html { render :new }
        format.js { render }
      end
    end
  end

  def edit
  end

  def update
    @ingredient.update ingredient_params
    redirect_to new_ingredient_path
  end

  def destroy
    @ingredient.destroy
  end

private

  def find_ingredient
    @ingredient = Ingredient.find params[:id]
  end

  def ingredient_params
    params.require(:ingredient).permit(:name, :category)
  end

end

app/controllers/shelves_controller.rb
class ShelvesController < ApplicationController

before_action :find_shelf, only: [:show, :edit, :update]

  def index
  end

  def show
    @shelf = Shelf.find params[:id]
    @ingredients = Ingredient.all
    @drinks = Drink.all
  end

  def new
    @shelf = Shelf.new
  end

  def create
    @shelf = Shelf.new
      if @shelf.save
        redirect_to @shelf
      else
        render :new
      end
  end

  def edit
  end

  def update
    if @shelf.update shelf_params
      redirect_to @shelf
    else
      render :edit
    end
  end

  def add_ingredient
    respond_to do |format|  
      @shelf = Shelf.find params[:shelf_id]
      @ingredient = Ingredient.find params[:id]
      @shelf.ingredients << @ingredient
      @shelf.save
      format.html { render :back }
      format.js { render }
    end
  end

  def remove_ingredient
    @shelf = Shelf.find params[:shelf_id]
    @ingredient = Ingredient.find params[:id]
    @shelf.ingredients.delete(@ingredient)
    @shelf.save
    redirect_to(:back)
  end

private

  def find_shelf
    @shelf = Shelf.find params[:id]
  end

  def shelf_params
    params.require(:shelf).permit({ingredient_ids: []})
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/drinks_helper.rb
module DrinksHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/shelfs_helper.rb
module ShelfsHelper
end

app/views/drinks/_form.html.erb
<div class="container white-text">
  
  <div class="col-md-6">
    <h3>New Drink</h3>
      <%= simple_form_for @drink do |f| %>
      <%= f.input :name, placeholder: "Enter a drink name..." %>
      <%= f.input :description, placeholder: "Enter the instructions for the new drink.." %>
      <%= f.button :submit %>
      <br>
  </div>

      <div id="ingredients" class="col-md-6">
          <h3>Add Ingredients</h3>
          <%= f.simple_fields_for :ingredients do |ingredient| %>
            <%= render 'ingredient_fields', :f => ingredient %>
          <% end %>
        <div class="links">
          <br>
            <%= link_to_add_association 'Add Ingredient', f, :ingredients, class: "btn btn-default" %>
        </div>
          <% end %>
      </div>
</div>

app/views/drinks/_ingredient_fields.html.erb
<div class="nested-fields">
  <%= f.input :name %>
  <%= f.input :category, collection: [ "Spirit", "Liqueur", "Mix", "Pop Mix"], class: "ingredient_field" %>
  <%= link_to_remove_association "Remove Ingredient", f, class: "btn btn-default" %>
</div>

app/views/drinks/index.html.erb
<div class="container" id="drink_index_container">
  <% @drinks.order(:name).each do |d| %>

      <div class="col-md-2 liq-drink text-center shadowed white-text">
        <div class="drinktext col-md-12">
         <%= link_to d.name, d %>
        </div>
        <div class="col-md-12 drink_ingredients text-center white-text alt-font">
          <%= simple_format d.description %>
          <br>
        </div>
      </div>

  <% end %>
</div>

app/views/drinks/show.html.erb
<div class="container">

  <div class="col-md-12 main-font white-text large-text">
    <div class="col-md-3 text-center"> 
      <%= @drink.name %>
    </div>
    <hr>
  </div>


    <div class="col-md-1"> </div>
  <div class="col-md-6 white-text small-text alt-font">
    <%= simple_format @drink.description %>
  </div>

</div>

app/views/ingredients/_ingredient.html.erb
<div id="<%= dom_id(ingredient) %>">
  <%= ingredient.name %>
  <hr>
</div>

app/views/ingredients/create.js.erb
$(".ingredients_list").prepend("<%= j render partial: '/ingredients/ingredient', locals: {ingredient: @ingredient} %>");
$(".ingredient_field").val("");

app/views/ingredients/new.html.erb
<div class="container">
  <div class="col-md-6 white-text">
    <%= simple_form_for @ingredient, remote: true do |f| %>
    <%= f.input :name, class: "ingredient_field" %>
    <%= f.input :category, collection: [ "Spirit", "Liqueur", "Mix", "Pop Mix"], class: "ingredient_field" %>
    <%= f.button :submit, class: "btn btn-warning" %>
    <% end %>
  </div>

  <div class="col-md-6 text-center ingredients_list alt-font">
    <% @ingredients.order(:name).each do |i| %>
        <%= render partial: "ingredients/ingredient", locals: { ingredient: i } %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Liqs</title>
  <%= stylesheet_link_tag    'application', media: 'all'%>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="nav-header">

  <div class="col-md-6 site-title text-center">
    Liqs
  </div>
  <div class="col-md-6 nav-logo-text text-center">
    <%= link_to "START HERE", shelves_path, method: :post, class: "nav-link" %>
    <%= link_to "ALL DRINKS", drinks_path, class: "nav-link" %>
  </div>

</div>

<%= yield %>

</body>
</html>

app/views/shelves/_form.html.erb
<%= simple_form_for @shelf do |f| %>
<%= f.association :ingredients, as: :check_boxes %>
<%= f.button :submit %>
<% end %>

app/views/shelves/_ingredient.html.erb
<div class="col-md-2 liq-ing shadowed text-center">    

    <div class="remove_ingredient col-md-12 white-text text-left">
      <%= link_to "x", remove_ingredient_path(@shelf, i) %>
    </div>

    <% if i.category == "Spirit" %> 
      <%= image_tag ("bottle_fat.png"), class: "bottle" %>  
    <% elsif i.category == "Liqueur" %> 
      <%= image_tag ("bottle_tall.png"), class: "bottle" %>
    <% elsif i.category == "Mix" %> 
      <%= image_tag ("bottle_mix.png"), class: "bottle" %>
    <% else %>
      <%= image_tag ("bottle_popmix.png"), class: "bottle" %>
    <% end %>

  <div class="liqtext alt-font">
    <%= i.name %>
  </div>

</div>

<script>
  $('.liq-ing').hover( function () {

    $(this).css('border-color', 'red');
    $(this).find('.remove_ingredient').fadeIn('fast');

  }, function () {

    $(this).css('border-color', '#e8d136');
    $(this).find('.remove_ingredient').fadeOut('fast');

  });

    $('.remove_ingredient a').hover( function () {

      $(this).css('color', 'red');

    }, function () {

      $(this).css('color', 'white');

    });

    $('a').css('text-decoration', 'none');

</script>

app/views/shelves/add_ingredient.js.erb
var l = $("<%= j render partial: '/shelves/ingredient', locals: {i: @ingredient} %>");
$(".shelved_ingredients").append(l);

setTimeout(function() {
  $('.liq-ing').addClass('show');
}, 1);

// SUBMIT BOX VALUE
var drinksCount = $('.liq-drink').size()


if( drinksCount == 0 ) {
  $('#drink_counter').text("CLICK HERE WHEN YOU ARE FINISHED");
}
  else {
  $('#drink_counter').text(drinksCount + " DRINKS TO VIEW");
}

// SUBMIT BOX HOVER
  $('#submit_box').hover( function () {

    $(this).css('border-color', '#9AFE2E');
    $(this).css('color', '#9AFE2E');

  }, function () {

    $(this).css('border-color', '#e8d136');
    $(this).css('color', 'white');

  });

    

app/views/shelves/edit.html.erb
<%= render "form" %>

app/views/shelves/show.html.erb
<div class="container" id="shelf-container">
  <div class="row">
    
    <!-- INGREDIENT ADDER -->
    <div class="col-md-3 liqs_adder alt-font white-text">
      
      <br>
        ADD INGREDIENTS TO YOUR SHELF
    
      <div class="col-md-12">
         <form>
          <br>
          <input class="form-control" id="ingredient_search" type="text"/>
        </form>
      </div>
      
      <div class="col-md-12">
        <br>
        <hr>
      </div>

      <div class="col-md-12 shelf-ingredients text-center">
          <% @ingredients.order(:name).each do |i| %>
            <div class="ingli">
              <%= link_to i.name, add_ingredient_path(@shelf, i), remote: true %>
              <br>
            </div>
          <% end %>
      </div>
    </div>

    <!--  SHELFED INGREDIENTS -->

    <div class="col-md-2 shadowed text-center white-text large-text alt-font" id="submit_box">
      <span class="glyphicon glyphicon-ok"></span>
      <h5 id="drink_counter"> Submit </h5>
    </div>

    <div class="shelved_ingredients">
      
      <% @shelf.ingredients.order(:name).each do |i| %>
        <%= render partial: "/shelves/ingredient",  locals: { i: i} %>
      <% end %>
    
    </div>
  </div>
</div>

<div class="container" id="drink_container">

    <div class="col-md-2 shadowed text-center white-text large-text alt-font" id="edit_box">
        <h3><span class="glyphicon glyphicon-chevron-up">
          <div class="col-md-12 edit_text alt-font">
            BACK
          </div>
        </span></h3>
    </div>

<div class="drinkload">
  <% @drinks.each do |d| %>

    <% di_array = d.ingredients.map { |di| di.name } %>
    <% sh_array = @shelf.ingredients.map { |j| j.name } %>

    <% if di_array & sh_array == di_array %>

      <div class="col-md-2 liq-drink text-center shadowed white-text">
        <div class="drinktext col-md-12">
         <%= link_to d.name, d %>
        </div>
        <div class="col-md-12 drink_ingredients text-center white-text alt-font">
          <%= simple_format d.description %>
          <br>
        </div>
      </div>

    <% end %>



  <% end %>
</div>
</div>